// swift-tools-version: 6.0
//
// HyperGitCore — core library for the HyperGit mobile app.
// Backend-agnostic domain layer: models, networking, auth, clients (GitHub/Linear),
// persistence protocols and the UI store. Built by `swift build` / `swift test` on
// macOS host (v14+) and linked into the iOS app target (v17+) generated by xcodegen.

import PackageDescription

let package = Package(
    name: "HyperGitCore",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [
        .library(name: "HyperGitCore", targets: ["HyperGitCore"]),
        .executable(name: "HyperGitApp", targets: ["HyperGitApp"]),
    ],
    targets: [
        .target(
            name: "HyperGitCore",
            path: "Sources/HyperGitCore"
        ),
        .executableTarget(
            name: "HyperGitApp",
            dependencies: ["HyperGitCore"],
            path: "App"
        ),
        .testTarget(
            name: "HyperGitCoreTests",
            dependencies: ["HyperGitCore"],
            path: "Tests/HyperGitCoreTests"
        ),
    ]
)
