// swift-tools-version: 6.0
//
// HyperGitCore — core library for the HyperGit mobile app.
// Backend-agnostic domain layer: models, networking, auth, clients (GitHub/Linear),
// persistence protocols and the UI store. Built by `swift build` / `swift test` on
// macOS host (v14+) and linked into the iOS app target (v17+) generated by xcodegen.

import PackageDescription
import Foundation

#if os(macOS)
func selectedDeveloperDirectory() -> String? {
    if let developerDirectory = ProcessInfo.processInfo.environment["DEVELOPER_DIR"],
       !developerDirectory.isEmpty {
        return developerDirectory
    }

    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/xcode-select")
    process.arguments = ["-p"]
    let output = Pipe()
    process.standardOutput = output
    process.standardError = Pipe()

    do {
        try process.run()
        process.waitUntilExit()
    } catch {
        return nil
    }

    guard process.terminationStatus == 0 else { return nil }
    let data = output.fileHandleForReading.readDataToEndOfFile()
    let path = String(data: data, encoding: .utf8)?
        .trimmingCharacters(in: .whitespacesAndNewlines)
    return path?.isEmpty == false ? path : nil
}

let developerDirectory = selectedDeveloperDirectory()
let testingFrameworksPath = developerDirectory.map { "\($0)/Library/Developer/Frameworks" }
let testingRuntimePath = developerDirectory.map { "\($0)/Library/Developer/usr/lib" }

let swiftTestingSettings: [SwiftSetting]
let swiftTestingLinkerSettings: [LinkerSetting]

if let testingFrameworksPath,
   FileManager.default.fileExists(atPath: "\(testingFrameworksPath)/Testing.framework") {
    // Apple CLT exposes Swift Testing outside the default framework search paths.
    swiftTestingSettings = [
        .unsafeFlags(["-F", testingFrameworksPath], .when(platforms: [.macOS])),
    ]

    var linkerFlags = [
        "-F", testingFrameworksPath,
        "-Xlinker", "-rpath",
        "-Xlinker", testingFrameworksPath,
    ]
    if let testingRuntimePath,
       FileManager.default.fileExists(atPath: testingRuntimePath) {
        linkerFlags.append(contentsOf: [
            "-Xlinker", "-rpath",
            "-Xlinker", testingRuntimePath,
        ])
    }
    swiftTestingLinkerSettings = [
        .unsafeFlags(linkerFlags, .when(platforms: [.macOS])),
    ]
} else {
    swiftTestingSettings = []
    swiftTestingLinkerSettings = []
}
#else
let swiftTestingSettings: [SwiftSetting] = []
let swiftTestingLinkerSettings: [LinkerSetting] = []
#endif

let package = Package(
    name: "HyperGitCore",
    platforms: [.macOS(.v14), .iOS(.v17)],
    products: [
        .library(name: "HyperGitCore", targets: ["HyperGitCore"]),
        .executable(name: "HyperGitApp", targets: ["HyperGitApp"]),
    ],
    targets: [
        .target(
            name: "HyperGitCore",
            path: "Sources/HyperGitCore"
        ),
        .executableTarget(
            name: "HyperGitApp",
            dependencies: ["HyperGitCore"],
            path: "App",
            exclude: ["Info.plist"]
        ),
        .testTarget(
            name: "HyperGitCoreTests",
            dependencies: ["HyperGitCore"],
            path: "Tests/HyperGitCoreTests",
            swiftSettings: swiftTestingSettings,
            linkerSettings: swiftTestingLinkerSettings
        ),
    ]
)
